import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

console.log("Starting esbuild build...");
console.log("Production mode:", prod);

if (prod) {
	console.log("Building...");
	await esbuild.build({
		banner: {
			js: banner,
		},
		entryPoints: ["src/main.ts"],
		bundle: true,
		external: [
			"obsidian",
			"electron",
			"@codemirror/autocomplete",
			"@codemirror/collab",
			"@codemirror/commands",
			"@codemirror/language",
			"@codemirror/lint",
			"@codemirror/search",
			"@codemirror/state",
			"@codemirror/view",
			"@lezer/common",
			"@lezer/highlight",
			"@lezer/lr",
			...builtinModules],
		format: "cjs",
		target: "es2018",
		logLevel: "info",
		sourcemap: false,
		treeShaking: true,
		outfile: "dist/main.js",
		minify: true,
	});
	console.log("Build complete!");
	process.exit(0);
} else {
	const context = await esbuild.context({
		banner: {
			js: banner,
		},
		entryPoints: ["src/main.ts"],
		bundle: true,
		external: [
			"obsidian",
			"electron",
			"@codemirror/autocomplete",
			"@codemirror/collab",
			"@codemirror/commands",
			"@codemirror/language",
			"@codemirror/lint",
			"@codemirror/search",
			"@codemirror/state",
			"@codemirror/view",
			"@lezer/common",
			"@lezer/highlight",
			"@lezer/lr",
			...builtinModules],
		format: "cjs",
		target: "es2018",
		logLevel: "info",
		sourcemap: "inline",
		treeShaking: true,
		outfile: "dist/main.js",
		minify: false,
	});
	await context.watch();
}
